### ISSUE TITLE
Scorecard `pxb-action-items` should be more Robust

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/angular-component-library#235]
#### Describe the desired behavior
It would be nice if the ScoreCard's `pxb-action-items` could accept more than just top-level `mat-icons` to work.

#### Describe the current behavior
If someone passes in anything other than just mat-icons (e.g. a div + mat-icons, or mat-buttons), then the RTL margins and styles will break. 

This does not work. 
```
<div pxb-action-items>
    <div *ngFor="let action of actions; index as i;">
        <mat-icon *ngIf="i < actionLimit" (click)="actionClick(actions[i])">
          {{actions[i]}}
        </mat-icon>
    </div>
</div>
```

Renders this:
![image](https://user-images.githubusercontent.com/6538289/109973304-3d5ff600-7cc6-11eb-88fe-8280c2fa4ae3.png)

But this works, because ng-content doesn't render as a element and works with our current sass rules: 
```
<ng-container pxb-action-items>
  <ng-container *ngFor="let action of actions; index as i;">
      <mat-icon *ngIf="i < actionLimit" (click)="actionClick(actions[i])">
          {{actions[i]}}
      </mat-icon>
  </ng-container>
</ng-container>
```

Renders this: 
![image](https://user-images.githubusercontent.com/6538289/109973383-536db680-7cc6-11eb-8c31-f94ca9d0b4f0.png)

#### Is this request related to a current issue?
No

**Comment by jeffvg** [comment]
This has something to do with top level content.

**Comment by joebochill** [comment]
Do we really need to support them passing in any arbitrary wrapper elements, or can this simply be a documentation update to tell them to use ng-container if they need to dynamically create items with ngFor?

**Comment by emclaug2** [comment]
I'm closing this issue since,

1. No one else is asking for this feature besides me
2. This case is covered in our documentation site rewrite
3. It's not a priority nor neccessary
