### ISSUE TITLE
Storybook build error

### ISSUE THREAD

**Issue by jeffvg** [brightlayer-ui/angular-component-library#275]
#### Describe the bug
Running "yarn start:storybook" throws errors in the terminal after linking components.

Error: Cannot find module '@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs'
ERR! Require stack:
ERR! -/pxblue/angular-component-library/demos/storybook/node_modules/@storybook/angular/dist/server/angular-cli_utils.js
ERR! -/pxblue/angular-component-library/demos/storybook/node_modules/@storybook/angular/dist/server/angular-cli_config.js
ERR! -/pxblue/angular-component-library/demos/storybook/node_modules/@storybook/angular/dist/server/framework-preset-angular-cli.js
ERR! -/pxblue/angular-component-library/demos/storybook/node_modules/@storybook/core/dist/server/presets.js
ERR! -/pxblue/angular-component-library/demos/storybook/node_modules/@storybook/core/dist/server/config.js
ERR! -/pxblue/angular-component-library/demos/storybook/node_modules/@storybook/core/dist/server/build-static.js
ERR! -/pxblue/angular-component-library/demos/storybook/node_modules/@storybook/core/server.js
ERR! -/pxblue/angular-component-library/demos/storybook/node_modules/@storybook/angular/dist/server/index.js
ERR! -/pxblue/angular-component-library/demos/storybook/node_modules/@storybook/angular/bin/index.js
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
ERR!     at Module.require (internal/modules/cjs/loader.js:952:19)
ERR!     at require (internal/modules/cjs/helpers.js:88:18)
ERR!     at Object.<anonymous> (/pxblue/angular-component-library/demos/storybook/node_modules/@storybook/angular/dist/server/angular-cli_utils.js:19:25)
ERR!     at Module._compile (internal/modules/cjs/loader.js:1063:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:928:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
ERR!     at Module.require (internal/modules/cjs/loader.js:952:19)
ERR!     at require (internal/modules/cjs/helpers.js:88:18)
ERR!     at Object.<anonymous> (/pxblue/angular-component-library/demos/storybook/node_modules/@storybook/angular/dist/server/angular-cli_config.js:29:27)
ERR!     at Module._compile (internal/modules/cjs/loader.js:1063:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:928:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:769:14)

#### What is the expected behavior?
Run without error and warning
#### What are the steps to reproduce?
1. yarn start:storybook
2. view output in terminal

**Comment by huayunh** [comment]
The second half (updating existing whatever) is an internal issue and is looked at somewhere else; first half looks attention worthy

**Comment by joebochill** [comment]
Updated the description to remove the second piece that's covered elsewhere (storybook issue)

**Comment by emclaug2** [comment]
This is an issue that we've been living with for about 6 months now and we are transitioning away from the idea of maintaining our library in Storybook 5.
