### ISSUE TITLE
Showcase Initialization Issue

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/angular-component-library#317]
#### Describe the bug
Cloning fresh repo & running storybook before showcase causes showcase to not initialize. 

#### What is the expected behavior?
Our initialization script should be smart enough to initialize the showcase folder even when the folder isn't empty.
This is because after the start:storybook command is ran, the showcase folder is no longer empty (?).  The command fails because the showcase folder is not empty by the time initialization occurs. 

#### What are the steps to reproduce?
1.  Clone the repo
2. Run `yarn start:storybook`
3. Run `yarn start:showcase` & see error. 

#### Environment

Windows		

#### Anything else to add?
Possible solution:  Run a command to empty the node_modules folder before attempting to initialize if the folder is not empty.

**Comment by emclaug2** [comment]
Run the initialization script as the first part of the `start:storybook` command.

**Comment by emclaug2** [comment]
Check to make sure this isn't happening in the React & RN component libraries.

**Comment by ektasawant** [comment]
Followed below steps:
1. Clone repo and checkout to fix branch
2. run yarn start:storybook
3. run yarn start:showcase

getting following error:
<img width="925" alt="Screenshot 2022-01-07 at 5 30 46 PM" src="https://user-images.githubusercontent.com/10433274/148542201-44409f43-8e3d-4b22-84e9-f1aaf4f3c947.png">

Anything I missed?
