### ISSUE TITLE
Specify Required Peer Deps 

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/angular-component-library#351]
#### Describe the desired behavior
Specify a peer dependency of @angular/core^12.0.0 & @angular/material^12.0.0 & @angular/cdk^12.0.0 in the list of peer dependencies

#### Describe the current behavior
There are no references to which versions of angular are required for this library to run. 

#### Is this request related to a current issue?
No

#### Additional Context

Issue introduced in v5.0.0 of the @pxblue/angular-component-library

**Comment by joebochill** [comment]
Let's make sure the package.json is correct and also mention the peer dependencies in the Readme.
