### ISSUE TITLE
Collapsible AppBar Should Handle Scroll Element Changes

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/angular-component-library#362]
#### Describe the bug
This component expects to be fed either a scrollable element id, className or the element itself.  But if you provide an element that is populated `ngAfterViewInit`, the component will not update the scroll element.

#### What is the expected behavior?
Make it so that I can provide a scroll element `ngAfterViewInit`.  

Example:

```
// Parent Component
    scrollEl: Element;

    ngAfterViewInit(): void {
        this.scrollEl = document.getElementsByClassName('mat-sidenav-content')[0];  
        this._ref.detectChanges();
    }

```

In the example above, I want the sidenav content to be the scrollable element, but the app bar component will continue to use the default `undefined. 

#### What are the steps to reproduce?
...

#### Environment

Windows Chrome
		
#### Anything else to add?
You can work around this by providing the className of the element you want to use instead, it's just confusing that this works and directly passing in the element doesn't.

**Comment by emclaug2** [comment]
If you want to provide a scrollable element, that element must exist on the screen before you the collapsible appbar is rendered.

**Comment by joebochill** [comment]
@emclaug2 Is this fixable? If it's not fixable, is it just a documentation change to explain your previous comment to users? Do we need to drop support for passing in elements directly?

**Comment by emclaug2** [comment]
> @emclaug2 Is this fixable? If it's not fixable, is it just a documentation change to explain your previous comment to users? Do we need to drop support for passing in elements directly?

This one only required us to unsubscribe & then subscribe to new scroll elements on Id | Class | Element changes.
