### ISSUE TITLE
Add a ToolbarMenu component

### ISSUE THREAD

**Issue by joebochill** [brightlayer-ui/angular-component-library#374]
#### Describe the desired behavior
This will be a replacement for the existing DropdownToolbar component. We will build a generic component that will handle the dropdown arrow iconography and state and trigger the menu open and closed. The user will supply ng-content for the label (could be text, could be icon + text, etc.) and we will append the dropdown arrow beside their content. Clicking the content will open the menu provided by the user (also supplied via ng content). Most of this functionality can simply be taken out of the existing dropdown toolbar.

Remove the DropdownToolbar component. Make sure that instructions for using the new approach is mentioned in the readme for the Appbar component (e.g., as an example).

#### Describe the current behavior
Rather than having this functionality built into a Toolbar, we will isolate it into a smaller sub-component that can be used in any toolbar (regular mat toolbar, blui collapsible, etc.)

#### Is this request related to a current issue?
No

**Comment by emclaug2** [comment]
This is fixed in #402; closing this.
