### ISSUE TITLE
Support for Angular 13

### ISSUE THREAD

**Issue by joebochill** [brightlayer-ui/angular-component-library#375]
#### Describe the desired behavior
Component library should be built using Angular 13 and work seamlessly in Angular 13 projects.

#### Describe the current behavior
Using Angular 12. Trying to use the library in a new Angular 13 project causes some issues with imports.

#### Is this request related to a current issue?
This is reported by the PredictPulse team.

**Comment by jeffvg** [comment]
@emclaug2 is looking into this with upgrade work.

**Comment by emclaug2** [comment]
#396 Addresses this.

**Comment by emclaug2** [comment]
Fixed in #396
