### ISSUE TITLE
Check dependencies and security vulnerabilities

### ISSUE THREAD

**Issue by joebochill** [brightlayer-ui/angular-component-library#376]
#### Describe the desired behavior
Make sure we are using the latest versions of dependencies and that we do not have any high or severe security vulnerabilities.

#### Describe the current behavior
May be using some older packages.

#### Is this request related to a current issue?
No

**Comment by emclaug2** [comment]
This should be resolved now; we've updated to angular 13 dependencies & our showcase is updated weekly.
