### ISSUE TITLE
Empty State content is not centered when a description is not provided

### ISSUE THREAD

**Issue by daileytj** [brightlayer-ui/angular-component-library#378]
#### Describe the bug
Whenever the description is not provided, there is still margin-bottom applied which off-centers the empty-state component.  
#### What is the expected behavior?
Empty State content should be centered regardless of description

#### What are the steps to reproduce?
1. run storybook
2. go to an empty state story without a description
3. inspect element and observe bottom margin on the description element causing the empty state content to render off-center.

#### Screenshots or links to minimum reproduction example

<img width="362" alt="Screen Shot 2022-01-04 at 10 58 48 AM" src="https://user-images.githubusercontent.com/6538289/148087376-9704f8fa-89d1-45f9-84e0-48394b256f62.png">

**Comment by daileytj** [comment]
I made a fix for this, but it's not very elegant. I would like someone else to take a look at this before making a PR with my solution. 

https://github.com/brightlayer-ui/angular-component-library/tree/bug/378-center-empty-state

**Comment by emclaug2** [comment]
Fixed in #437
