### ISSUE TITLE
Drawer nav item regression in 6.0.2

### ISSUE THREAD

**Issue by julien-von-oetinger** [brightlayer-ui/angular-component-library#391]
#### Describe the bug

In the 6.0.2 version, if you set the attribute ```expaned``` to ```true``` on a ```blui-drawer-nav-item``` the children of that item will not appear upon initialization (see screenshots).

#### What is the expected behavior?

The children of an exanded item should appear upon initialization.

#### What are the steps to reproduce?

Defined a ```blui-drawer-nav-item``` with ```[expanded]="true"``` and children items.

#### Screenshots or links to minimum reproduction example

In 6.0.0 it was working fine:

![6 0 0](https://user-images.githubusercontent.com/55489938/150954859-6543a0a9-7d8c-4faf-9b7e-aecf5026fb02.png)

But in 6.0.2 a regression appeared:

![6 0 2](https://user-images.githubusercontent.com/55489938/150954932-15f49b88-3c59-4ce0-a40f-7cdc30e4d5d9.png)

![6 0 2](https://user-images.githubusercontent.com/55489938/150954954-fe61c541-294b-486a-9ea5-b74a719d44c7.gif)

#### Environment

I got the issue after upgrading from 6.0.0 to 6.0.2.

Here are the brightlayer dependancies I have:

```
    "@brightlayer-ui/angular-components": "6.0.2",
    "@brightlayer-ui/angular-themes": "6.3.0",
    "@brightlayer-ui/colors": "3.0.1",
    "@brightlayer-ui/icons": "1.8.1",
    "@brightlayer-ui/ng-progress-icons": "1.2.1",
```
		
#### Anything else to add?

For now I have downgraded back to 6.0.0

**Comment by emclaug2** [comment]
@julien-von-oetinger Could you please try our new beta package in your application to check to see if the issue has been addressed?

`npm i @brightlayer-ui/angular-components@6.0.3-beta.0`

https://www.npmjs.com/package/@brightlayer-ui/angular-components/v/6.0.3-beta.0

**Comment by julien-von-oetinger** [comment]
@emclaug2 I have tried the beta package and the issue seems to be fixed 👍

**Comment by emclaug2** [comment]
Thanks for trying it out, @julien-von-oetinger! We will get this beta package published as latest and then close this issue.
