### ISSUE TITLE
Strange Transition Color in AppBar

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/angular-component-library#395]
#### Describe the bug
Color Transitions slowly from black to white on init.

#### What is the expected behavior?
No transition.

#### What are the steps to reproduce?
Load storybook and refresh on an appbar story. 

#### Screenshots or links to minimum reproduction example
![Transition Color](https://user-images.githubusercontent.com/6538289/152702218-452088bd-8661-42a5-bc5e-2d28cfa10bed.gif)

#### Environment

Chrome Windows

**Comment by huayunh** [comment]
I didn't run any experiments. My guess is that this line
https://github.com/brightlayer-ui/angular-component-library/blob/b6ec0fb79926939bb4458594f89b3f265ddb0c5d/components/src/core/app-bar/app-bar.component.scss#L9

should not say `all` in the CSS rules.

Perhaps `all .3s, color 0s;` might work?

**Comment by emclaug2** [comment]
Fixed in #409
