### ISSUE TITLE
Incorrect typography styles on EmptyState component

### ISSUE THREAD

**Issue by daileytj** [brightlayer-ui/angular-component-library#414]
#### Describe the bug
Looks like the new typography rules in `ng-themes@7.0.0` has affected our empty state styles; Adjust the EmptyState component to use the correct `mat-` class & apply a line-height.

#### What is the expected behavior?
Typography styles should match our typography definitions.

#### Screenshots or links to minimum reproduction example
<img width="395" alt="Screen Shot 2022-03-07 at 3 03 35 PM" src="https://user-images.githubusercontent.com/13989985/157249179-02438380-05aa-49ec-a598-6c1bfb224dff.png">

**Comment by huayunh** [comment]
I just did the master merge and this is still not auto-closed. It looks like this will only be auto-closed if the branch merged to is the default branch?
