### ISSUE TITLE
Drawer disappears on double escape. 

### ISSUE THREAD

**Issue by JeanMeche** [brightlayer-ui/angular-component-library#426]
#### Describe the bug
The drawer disappears when hitting escape twice. 

This is reproducible on this storybook example : https://brightlayer-ui-components.github.io/angular/?path=/story/components-drawer--within-a-drawer-layout

#### Screenshots or links to minimum reproduction example

![image](https://user-images.githubusercontent.com/1300985/163573837-2c24f3e8-5bed-4ff0-a94d-61abff12593e.png)

**Comment by jeffvg** [comment]
Verified the same within ng showcase demo

**Comment by emclaug2** [comment]
Thanks for reporting this issue @JeanMeche; this is a good catch.  We'll aim to have this fixed in `@brightlayer-ui/angular-components@7.0.2`.

**Comment by emclaug2** [comment]
Fixed in #435 
There's a beta package published that can be used for testing: @brightlayer-ui/angular-components@7.0.2-beta.1
