### ISSUE TITLE
Rail footer looking strange in storybook

### ISSUE THREAD

**Issue by huayunh** [brightlayer-ui/angular-component-library#448]
#### Describe the bug

https://brightlayer-ui-components.github.io/angular/?path=/story/components-drawer--with-a-nav-rail

The Eaton logo in the footer is ridiculously small
![image](https://user-images.githubusercontent.com/8997218/179791455-d1d8abbc-a46b-49fd-ba86-7bb6bb5b3050.png)

#### What is the expected behavior?

making it 40px wide for dense variant, and 48px for regular variant

<img width="634" alt="image" src="https://user-images.githubusercontent.com/8997218/179791388-ed4b8056-8ef9-40eb-bde3-b58b2a68a541.png">

**Comment by bkarambe** [comment]
We wont be fixing old storybook issues.
