### ISSUE TITLE
Developer Docs Viewport Adjustment

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/angular-component-library#462]
#### Describe the bug
Content getting clipped on lower viewports.
https://github.com/brightlayer-ui/angular-component-library/pull/458#issuecomment-1198387464

#### What is the expected behavior?
No overflow should be happening.

#### What are the steps to reproduce?
1. Open dev-docs
2. Make window smaller until content overflows

#### Screenshots or links to minimum reproduction example
https://github.com/brightlayer-ui/angular-component-library/pull/458#issuecomment-1198387464

#### Environment

Chrome
		
#### Anything else to add?
Should we adjust the screen size at which the drawer variant changes?

**Comment by ektasawant** [comment]
Decide the viewport width for mobile view and then update it in Figma.

**Comment by emclaug2** [comment]
The Drawer now dismisses at 1280px.

**Comment by emclaug2** [comment]
This has been fixed in #467 but has not yet been updated in figma.

**Comment by emclaug2** [comment]
@ektasawant can you update the react side so dismiss drawer at 1280px?

**Comment by emclaug2** [comment]
This issue has been fixed, closing this one.
