### ISSUE TITLE
Match Figma Designs on Dev Docs

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/angular-component-library#485]
#### Describe the desired behavior
This is going to be a dump of all non-addressed issues from this PR: 
https://github.com/brightlayer-ui/angular-component-library/pull/481

1.  Fix the Drawer Subtitle to Match the Designs
![image](https://user-images.githubusercontent.com/6538289/188129110-04ce655b-feff-428a-8613-8ed3aecafbdc.png)

2.  Texts in the table of "API Docs" are not currently following our "monospaced" rules
3.   Quoted texts in API docs also need their styles adjusted

4.  Update Drawer sideBorder description knob; it's not entirely accurate within the context of a standalone-drawer. 
![image](https://user-images.githubusercontent.com/6538289/188132661-52deefa6-828d-46e8-b34f-dd5c86d27198.png)

5. Adjust this style (code blocks on examples page)
![image](https://user-images.githubusercontent.com/6538289/188137504-94e9d475-1dc5-4f49-9633-f117e9319091.png)

#### Describe the current behavior
It's close but not quite

#### Is this request related to a current issue?
No

**Comment by emclaug2** [comment]
Code block outline details are below:

<img width="775" alt="Screen Shot 2022-09-08 at 1 10 24 PM" src="https://user-images.githubusercontent.com/6538289/189183850-9d74c0f5-3bd2-42c4-bd83-fffe0c4f0215.png">

**Comment by huayunh** [comment]
BLUI-3516

**Comment by emclaug2** [comment]
This should be fixed now.
