### ISSUE TITLE
Angular 14 support

### ISSUE THREAD

**Issue by JeanMeche** [brightlayer-ui/angular-component-library#504]
#### Describe the desired behavior
Hi, do you expect to land Angular 14 support soon ? 

May I maybe provide some help for this ? 

Thx.

**Comment by emclaug2** [comment]
Hey Jean - we have plans to support angular 14 but it might have to wait until early next quarter.  If you're wanting to migrate to angular 14 earlier, we've had a team report back to us that they were able to upgrade to angular 14 while still using our current component libraries, but encountered a peer dependency version mismatch warning.

**Comment by JeanMeche** [comment]
Thanks for your feedback, I can confirm, everything is working fine with angular 14.
