### ISSUE TITLE
AppBar not listening for scroll events when rendered as a ng-template

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/angular-component-library#508]
#### Describe the bug
AppBar not listening for scroll events when rendered as a ng-template.
An attempt to listen for a scroll container is happening before the content is rendered on the screen.

#### What is the expected behavior?
Scroll element should be found by the Appbar component so snap variant works as expected.

#### What are the steps to reproduce?
1.  Create a `ng-template` with an app bar inside of it. (#appbar)
2.  Pass it into a template `<template [ngTemplateOutlet]="appbar">`
3. Observe `snap` variant does not work.

#### Screenshots or links to minimum reproduction example
![scrolllll](https://user-images.githubusercontent.com/6538289/191054152-0956729f-4d7c-4389-8bca-b9740f99324d.gif)

#### Environment

Chrome Windows	
	
#### Anything else to add?
No

**Comment by bkarambe** [comment]
Already been fixed.
