### ISSUE TITLE
Prevent svg overflow on EmptyState

### ISSUE THREAD

**Issue by JeanMeche** [brightlayer-ui/angular-component-library#530]
#### Describe the bug
The SVG might overflow the Empty state as a flex child: 

![image](https://user-images.githubusercontent.com/1300985/196123552-28b514e2-4ff4-45dc-9b24-bdeb3e866d35.png)

#### What are the steps to reproduce?
Demo: 
https://stackblitz.com/edit/angular-ivy-ecdisb?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.css

#### Suggested fix
The fix for this case is usual: allow a flex child to shrink with a min-height. 
Here that would be: 
```
.blui-empty-state-empty-icon-wrapper {
  min-height: 0; /* required to prevent overflow */
}
```

**Comment by daileytj** [comment]
@emclaug2 can you get some clarification on this issue?
